[package]
name = "minstant"
version = "0.0.2"
authors = ["The TiKV Authors"]
edition = "2018"

[dependencies]
ctor = "0.1.20"
minstant_macro = { path = "minstant_macro" }
smallvec = { version = "1.6", features = ["union","const_generics"] }

[workspace]
members = [ "minstant_macro" ]

[target.'cfg(not(target_os = "wasi"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "wasi")'.dependencies]
wasi = "0.7"

[dev-dependencies]
criterion = "0.3"
rand = "*"

[[bench]]
name = "now"
harness = false
